privileges:
  {
    1:
      {
        id: 1,
        name: "Full Access on all Companies",
        title_name: "User Management",
        title_id: 1,
      },
    2:
      {
        id: 2,
        name: "View User on my Company",
        title_name: "User Management",
        title_id: 1,
      },
    3:
      {
        id: 3,
        name: "Add Approver to User on my Project",
        title_name: "User Management",
        title_id: 1,
      },
    4:
      {
        id: 4,
        name: "Add Reviewers to User on my Project",
        title_name: "User Management",
        title_id: 1,
      },
    5:
      {
        id: 5,
        name: "Full Access on my Company",
        title_name: "User Management",
        title_id: 1,
      },
    6:
      {
        id: 6,
        name: "Full Access on User Group Management",
        title_name: "User Group Management",
        title_id: 2,
      },
    7:
      {
        id: 7,
        name: "View User Group Management",
        title_name: "User Group Management",
        title_id: 2,
      },
    9:
      {
        id: 9,
        name: "Full Access on Template Management",
        title_name: "Template Management",
        title_id: 4,

      },
    10:
      {
        id: 10,
        name: "View Template Management",
        title_name: "Template Management",
        title_id: 4,
      },
    13:
      {
        id: 13,
        name: "Full Access on schedule company",
        title_name: "Schedule Management",
        title_id: 5,
      },
    14:
      {
        id: 14,
        name: "Full Access on schedule project",
        title_name: "Schedule Management",
        title_id: 5,
      },
    15: 
      {
        id: 15,
        name: "Full Access on my CDS/CDP Assessment",
        title_name: "CDS/CDP Assessment",
        title_id: 10,
      },
    16:
      {
        id: 16,
        name: "Review CDS/CDP Assessment",
        title_name: "CDS/CDP Review",
        title_id: 6,
      },
    17:
      {
        id: 17,
        name: "Approve CDS/CDP Assessment",
        title_name: "CDS/CDP Review",
        title_id: 6,
      },
    24: 
    {
      id: 24,
      name: "View All CDS/CDP Assessment",
      title_name: "CDS/CDP Review",
      title_id: 6,
    },
    26: 
    {
      id: 26,
      name: "High level Review/Approve",
      title_name: "CDS/CDP Review",
      title_id: 6,
    },
    18:
    {
      id: 18,
      name: "Full Access on Level Mapping Management",
      title_name: "Level Mapping",
      title_id: 7      
    },

    19:
    {
      id: 19,
      name: "View Level Mapping Management",
      title_name: "Level Mapping",
      title_id: 7      
    },
    20:
    {
      id: 20,
      name: "Full Access on all Companies",
      title_name: "Dashboards",
      title_id: 8     
    },
    21:
    {
      id: 21,
      name: "Full Access on my Company",
      title_name: "Dashboards",
      title_id: 8     
    },
    22:
    {
      id: 22,
      name: "Full Access on my Project",
      title_name: "Dashboards",
      title_id: 8     
    },
    23:
    {
      id: 23,
      name: "View my Dashboard",
      title_name: "Dashboards",
      title_id: 8     
    },
    25:
    {
      id: 25,
      name: "Full Access on Organization Settings",
      title_name: "Organization Settings",
      title_id: 9     
    },
    
  }
